apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: external-service
      context: external-service
      docker:
    - image: demo-resilience
      custom:
        buildCommand: ./gradlew bootBuildImage --imageName=$IMAGE
        dependencies:
          paths:
            - build.gradle.kts
            - src/main/resources
            - src/main/k8s
            - build/classes
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "target/classes/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: target/classes/
deploy:
  kustomize:
    paths:
      - "src/main/k8s/"