spring:
  application:
    name: demo-resilience4j
  jackson:
    serialization:
      indent_output: true
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  health:
    probes:
      enabled: true


info:
  name: ${spring.application.name}
  description: resilience4j demo
  environment: ${spring.profiles.active}
  version: 0.0.1

services:
  serviceA:
    base-url: http://localhost:8081/
  serviceB:
    base-url: http://localhost:8082/

logging:
  root: debug