spring:
  application:
    name: demo-resilience4j
  jackson:
    serialization:
      indent_output: true
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false
server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, prometheus
  health:
    circuitbreakers.enabled: true
    probes.enabled: true
    ratelimiters.enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      distribution:
        percentiles-histogram:
          http:
            server.requests: true
          resilience4j:
            circuitbreaker:
              calls: true


info:
  name: ${spring.application.name}
  description: resilience4j demo
  environment: ${spring.profiles.active}
  version: 0.0.1

services:
  backendA:
    base-url: http://localhost:8081/
  backendB:
    base-url: http://localhost:8082/

logging:
  root: debug

# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slowCallRateThreshold: 100

      permittedNumberOfCallsInHalfOpenState: 3
      maxWaitDurationInHalfOpenState: 0
      minimumNumberOfCalls: 2

      slidingWindowSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - com.example.demoresilience.exception.BusinessException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.example.demoresilience.exception.BusinessException
  instances:
    backendA:
      baseConfig: default
    backendB:
      registerHealthIndicator: true
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordFailurePredicate: com.example.demoresilience.exception.RecordFailurePredicate