apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-circuitbreaker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    #- host: demo-circuitbreaker.minikube
    - host: demo-circuitbreaker.local-k8s
      http:
        paths:
          - path: /bootapp(/|$)(.*)
            backend:
              serviceName: demo-circuitbreaker
              servicePort: 80
          - path: /service-a(/|$)(.*)
            backend:
              serviceName: service-a
              servicePort: 80
          - path: /service-b(/|$)(.*)
            backend:
              serviceName: service-b
              servicePort: 80