apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  project: demo-circuitbreaker
resources:
  - bootapp-deployment.yml
  - services-deployment.yml
  - ingress.yml
configMapGenerator:
  - name: demo-circuitbreaker-config
    files:
      - config/application.yml