apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  project: demo-circuitbreaker
resources:
  - demo-service-deployment.yml
  - services-deployment.yml
  - prometheus-deployment.yml
  - ingress.yml
configMapGenerator:
  - name: demo-service-config
    files:
      - config/demo/application.yml
  - name: prometheus-config
    files:
      - config/prometheus/prometheus.yml
  - name: grafana-config
    files:
      - config/grafana/dashboard.json
  - name: service-a-config
    files:
      - config/service-a/config.js
  - name: service-b-config
    files:
      - config/service-b/config.js
